openapi: 3.0.0
info:
  title: Communication-Service API
  description: This is documentation made for communication service.
  version: 0.1.9
servers:
  - url: http://localhost:4000
    description: This is my local server

paths:
  /livecheck:
    description: Livecheck
    get:
      responses:
        200:
          description: Successful response



